// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfjibmrifkrulxuaguxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmamlibXJpZmtydWx4dWFndXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjE1OTUsImV4cCI6MjA2MTMzNzU5NX0.qHUZGWrwiN0CaMRa9uGqjx2HJayP7I_NGWjBabUjVFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);